name: Subdomain Finder 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOMAIN: 'sharda.ac.in'

jobs:
  recon:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19 
    
    - name: Install Required Tools 
      run: |
        go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
        sudo apt-get update
        sudo apt-get -y install python3 python3-pip
        sudo pip3 install requests argparse dnspython
        git clone https://github.com/aboul3la/Sublist3r.git ~/Sublist3r
        sudo snap install amass
      shell: bash

    - name: Run Sublist3r
      run: |
        echo "Target: $DOMAIN"
        python3 ~/Sublist3r/sublist3r.py -d $DOMAIN -o sublist3r_output.txt
      shell: bash

    - name: Run Subfinder
      run: |
        subfinder -d $DOMAIN -o subfinder_output.txt
      shell: bash

    - name: Run Amass
      run: |
        amass enum -d $DOMAIN -o amass_output.txt
      shell: bash
    
    - name: Sort Sub-domains
      run: |
        cat subfinder_output.txt sublist3r_output.txt amass_output.txt | sort -u | tee -a sorted_domains.txt
      shell: bash

    - name: Save results
      uses: actions/upload-artifact@v2
      with:
        name: Subdomains results
        path: subfinder_output.txt, sublist3r_output.txt, amass_output.txt, sorted_domains.txt
name: Subdomain Finder 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOMAIN: 'sharda.ac.in'

jobs:
  recon:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19 
    
    - name: Install Required Tools 
      run: |
        go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
        sudo apt-get update
        sudo apt-get -y install python3 python3-pip
        sudo pip3 install requests argparse dnspython
        git clone https://github.com/aboul3la/Sublist3r.git ~/Sublist3r
        sudo snap install amass
      shell: bash

    - name: Run Sublist3r
      run: |
        echo "Target: $DOMAIN"
        python3 ~/Sublist3r/sublist3r.py -d $DOMAIN -o sublist3r_output.txt
      shell: bash

    - name: Run Subfinder
      run: |
        subfinder -d $DOMAIN -o subfinder_output.txt
      shell: bash

    - name: Run Amass
      run: |
        amass enum -d $DOMAIN -o amass_output.txt
      shell: bash
    
    - name: Sort Sub-domains
      run: |
        cat subfinder_output.txt sublist3r_output.txt amass_output.txt | sort -u | tee -a sorted_domains.txt
      shell: bash

    - name: Save results
      uses: actions/upload-artifact@v2
      with:
        name: Subdomains results
        path: subfinder_output.txt sublist3r_output.txt amass_output.txt sorted_domains.txt
